### ISSUE TITLE
Please remove this information, it is not your data

### ISSUE THREAD

**Issue by ghost** [norvigaward/naward12#1]
https://github.com/norvigaward/naward12/search?q=rxskincenter&type=Code&utf8=%E2%9C%93

**Comment by evertlammerts** [comment]
Hi! I'm not sure whether I understand your request. Can you please tell us which content you believe we are not allowed to publish, why we are not allowed to publish it and what your relation to it is?

Note that all data published here are derivatives. The categories come from [DMOZ](http://www.dmoz.org/docs/en/about.html) and the domain names come from [Common Crawl](http://commoncrawl.org/terms-of-use/). I believe we are currently in accordance with their respective terms of use. If you believe that any of the published information in the file you refer to is not for them to share, then you may want to contact them directly. In the meantime I will close this issue. Feel free to re-open and comment with more information.
